### PR TITLE
NFIQ2 Exception Improvements 

### LINKED ISSUE #174: Remove unused exception error codes
There's too many NFIQException error codes, and most aren't used. Remove them.

### PR DESCRIPTION
**Pull request by afiglarz**
Closes #174 

Simplifies NFIQ2 Exceptions. Removes unused exceptions. Made enum class.

### CODE REVIEW

File: NFIQ2/NFIQ2Algorithm/src/features/FeatureFunctions.cpp [hunk 1]
```diff
@@ -558,8 +558,8 @@ NFIQ2::QualityFeatures::addSamplingFeatures(
 		if (canComputeValue) {
 			result.returnCode = 0;
 		} else {
-			result.returnCode =
-			    NFIQ2::e_Error_FeatureCalculationError;
+			result.returnCode = static_cast<int>(
+			    NFIQ2::ErrorCode::FeatureCalculationError);
```
Comment (gfiumara) [inline NFIQ2/NFIQ2Algorithm/src/features/FeatureFunctions.cpp:562]: returnCode != ErrorCode

File: NFIQ2/NFIQ2Algorithm/src/nfiq2/nfiq2_exception.cpp [hunk 2]
```diff
@@ -1,82 +1,18 @@
...
-	/* 52 */ "No minutiae have been found (min count = 0)",
-	/* 53 */ "Cannot get minutiae data",
-	/* 54 */ "Invalid NFIQ2 Score",
-	/* 55 */ "Invalid Image Size"
-};
-
-NFIQ2::NFIQException::NFIQException(uint32_t returnCode)
-    : m_ReturnCode(returnCode)
+NFIQ2::NFIQException::NFIQException(const NFIQ2::ErrorCode &errorCode)
+    : m_ReturnCode(static_cast<int>(errorCode))
```
Comment (gfiumara) [inline NFIQ2/NFIQ2Algorithm/src/nfiq2/nfiq2_exception.cpp:4]: Seriously? Change the type of `m_ReturnCode` ... and get rid of `m_`

File: NFIQ2/NFIQ2Algorithm/src/prediction/RandomForestML.cpp [hunk 3]
```diff
@@ -87,7 +87,7 @@ NFIQ2::Prediction::RandomForestML::initModule()
 		initModule(params);
 		return calculateHashString(params);
 	} catch (const cv::Exception &e) {
-		throw NFIQException(e_Error_UnknownError, e.msg);
+		throw NFIQException(UnknownError, e.msg);
```
Comment (gfiumara) [inline NFIQ2/NFIQ2Algorithm/src/prediction/RandomForestML.cpp:90]: Don't you need `NFIQ2::ErrorCode::` here?

**Review by gfiumara — CHANGES_REQUESTED** [review]

**Review by gfiumara — APPROVED** [review]
